name: Test workflow

on:
  push:
    branches:
      - branchB

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Print
      run: echo 'branch is B' ${{ github.ref }}
